import type { NextPage } from "next";
import Head from "next/head";

interface Props {
  title: string;
}

const Header: NextPage<Props> = ({ title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Header;
