import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import ReactTooltip from "react-tooltip";
import SimpleMap from "../components/SimpleMap";
import styles from "../styles/Home.module.css";

const Analytics: NextPage = () => {
  const [content, setContent] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Simple Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Simple Map</h1>

        <p className={styles.description}>blah, blah, blah</p>

        <div
          style={{
            width: "600px",
            height: "400px",
            outline: "1px solid gainsboro",
          }}
        >
          <SimpleMap setTooltipContent={setContent} />
          <ReactTooltip>{content}</ReactTooltip>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Analytics;
