import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

const Test: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Test Page</h1>

        <div className={styles.description}>Test contents</div>
      </main>

      <Footer />
    </div>
  );
};

export default Test;
